# Generated by Django 2.2.17 on 2021-01-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20210124_2100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
