# Generated by Django 2.2.17 on 2021-01-16 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_auto_20210116_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 13, 40, 43, 683832, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
