# Generated by Django 2.2.17 on 2021-01-20 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_auto_20210118_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuserprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 11, 56, 7, 618570, tzinfo=utc)),
        ),
    ]
