# Generated by Django 2.2.17 on 2021-01-24 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_auto_20210121_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 16, 12, 34, 842332, tzinfo=utc)),
        ),
    ]
